/**
 * Renders the landing page once per language from a single template.
 *
 *   node tools/buildPages.mjs
 *
 * Two real files come out — index.html and en/index.html — rather than one
 * page that swaps its own text. The reason is the audience: a link posted to
 * Hacker News, Reddit or Mastodon gets its preview card built by a crawler
 * that does not run scripts, so a page translated in the browser is always
 * previewed in whichever language the markup happened to ship in.
 *
 * The generated files are committed, so the host serves them with no build
 * step of its own. Edit src/, never the generated HTML — a note at the top of
 * each output says so, because that is the file people open first.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const src = path.join(root, 'src');

/** Absolute URLs are required for canonical and hreflang to mean anything. */
const SITE = (process.env.SITE_URL ?? 'https://zenmd.coding-afternoon.com').replace(/\/$/, '');

const read = (file) => readFileSync(path.join(src, file), 'utf8');
const template = read('page.html');
const styles = read('styles.css');
const script = read('page.js');

const languages = [
  { code: 'zh', out: 'index.html',    dir: '',    assets: '',    ogLocale: 'zh_TW' },
  { code: 'en', out: 'en/index.html', dir: 'en',  assets: '../', ogLocale: 'en_US' },
];

const urlFor = (dir) => (dir ? `${SITE}/${dir}/` : `${SITE}/`);

for (const language of languages) {
  const strings = JSON.parse(read(`strings.${language.code}.json`));
  const other = languages.find((candidate) => candidate !== language);
  const otherStrings = JSON.parse(read(`strings.${other.code}.json`));

  // The script carries placeholders of its own, and it is inserted through a
  // shorter key than they are — so resolve it before it joins the pile,
  // otherwise the pass is already over by the time it arrives.
  const resolvedScript = Object.keys(strings).reduce(
    (text, key) => text.split(`{{${key}}}`).join(strings[key]),
    script.trimEnd(),
  );

  const values = {
    ...strings,
    styles: styles.trimEnd(),
    script: resolvedScript,
    assets: language.assets,
    ogLocale: language.ogLocale,
    canonical: urlFor(language.dir),
    // Card images have to be absolute. A relative og:image is resolved by
    // some crawlers and dropped by others, and the ones that drop it are
    // the ones the link is being posted to.
    ogImage: `${SITE}/screenshots/04-zen-mode.png`,
    hrefZh: urlFor(''),
    hrefEn: urlFor('en'),
    // a link to the same page in the other language, relative so it works
    // from a file:// preview as well as from the host
    switchHref: language.dir === 'en' ? '../' : 'en/',
    switchLang: otherStrings.htmlLang,
    switchLabel: strings.switchLabel,
  };

  let page = template;
  // Longest keys first, so `h1` can never eat the start of `heroAlt`.
  for (const key of Object.keys(values).sort((a, b) => b.length - a.length)) {
    page = page.split(`{{${key}}}`).join(values[key]);
  }

  const missing = [...page.matchAll(/\{\{(\w+)\}\}/g)].map((match) => match[1]);
  if (missing.length) {
    console.error(`✕ ${language.out}: 沒有對應字串 → ${[...new Set(missing)].join(', ')}`);
    process.exitCode = 1;
    continue;
  }

  const banner = `<!-- Generated by tools/buildPages.mjs — edit src/, not this file. -->\n`;
  const target = path.join(root, language.out);
  if (language.dir) mkdirSync(path.join(root, language.dir), { recursive: true });
  writeFileSync(target, banner + page, 'utf8');
  console.log(`✓ ${language.out}  (${page.length} chars)`);
}

// Every key present in one language must be present in the other, or a page
// silently ships a stretch of the wrong language.
const zh = Object.keys(JSON.parse(read('strings.zh.json')));
const en = Object.keys(JSON.parse(read('strings.en.json')));
const onlyZh = zh.filter((key) => !en.includes(key));
const onlyEn = en.filter((key) => !zh.includes(key));
if (onlyZh.length || onlyEn.length) {
  console.error('✕ 兩份字串檔對不齊：');
  if (onlyZh.length) console.error('   只有中文有：', onlyZh.join(', '));
  if (onlyEn.length) console.error('   只有英文有：', onlyEn.join(', '));
  process.exitCode = 1;
} else {
  console.log(`✓ 兩份字串檔各 ${zh.length} 個 key，完全對齊`);
}
